#ifndef MAZE_STRUCTURES_H
#define MAZE_STRUCTURES_H
enum
{
    MAZE_STRUCTURE_EMPTY,
    MAZE_STRUCTURE_INTERSECTION,
    MAZE_STRUCTURE_HORIZONTAL,
    MAZE_STRUCTURE_VERTICAL
} maze_structures_E;
#endif
